<?php include("Templates/Includes/includesBeforeMain.php"); ?>

<main>

    <div class="Video-Saeule">
        <video src="/MediaFiles/Videos/UeberUns/Schattenkampf.mp4" controls>
            Ihr Browser kann dieses Video leider nicht wiedergeben.<br>
        </video>
    </div>

    <div class="decription_disciplines">

        <h1>Der Formenlauf, Kombinationen, Übungsfiguren</h1>

        <p>
            Hier ahmst du die Bewegung des Hand- und Fußkampfes gegen einen unsichtbaren (imaginären) Gegner nach.<br>
            Du übst die Bewegung in der Gruppe und kämpfst hier nicht gleich gegen einen richtigen Gegner, denn das würde dich beim Lernen neuer Techniken überfordern.<br>
            Bei diesem einzigartigen Konzept übst du die gleiche Technik, welche die fortgeschrittenen Sportler ausführen und kannst diese von ihnen nachahmen. Der Meister sieht sofort die kleinsten Fehler und korrigiert sie direkt – genial, typisch Taekwondo.<br>
            Zunehmend setzt du dich mit mehreren imaginären Gegnern, verschiedenen Angriffs- und Abfangvarianten auseinander.<br>
            Die Bewegungen sind in Verlauf, Energie, Endpunkt mit der richtigen Gewichtsverlagerung und exakter Atemkontrolle deines Körpers genauestens festgelegt – Tja, Taekwondo-typisch ein Höchstmaß ist hier das geistige Training und die Kontrolle: Ich sage dazu Bewegungsmeditation.<br>
            Du schaffst mit diesen Übungen das Fundament, die Grundlage deines Taekwondo; du übst dabei: Fleiß, Ausdauer, Genauigkeit, Bescheidenheit, Intensität, Kontrolle, Disziplin und erlernst dabei eine Hingabe, die dich im Leben sehr weit bringt.<br>
        </p>

        <h3>Wusstest du schon?</h3>

        Du übst alle Bewegung rechts und links gleichermaßen, das schafft einen körperlichen und seelischen Ausgleich.<br>
        Du trainierst bei den Taekwondo Übungsformen alle Muskeln – das führt zu einer geraden Körperhaltung, dadurch wirkst du auf deine Umwelt wesentlich selbstbewusster, das bringt richtig Pluspunkte bei Vorstellungsgesprächen.<br>
        Richtiges Atmen, auf das bei den Übungen besonderen Wert gelegt wird, schafft in Krisensituationen (Prüfungen, Vortrag) Sicherheit, Stabilität & Konzentration.<br>
        Du übst Parallel- und Diagonalbewegungen, das trainiert die rechte und linke Gehirnhälfte – aktives Gehirnjogging.<br>
        Bei Verletzungen wirkt sich das Üben von Bewegungsformen positiv auf den Heilungsprozess aus.

    </div>

</main>




<?php include("Templates/Includes/includesAfterMain.php"); ?>