<?php include("Templates/Includes/includesBeforeMain.php"); ?>

<main>

    <div class="Video-Säule">
        <video src="/MediaFiles/Videos/UeberUns/Schattenkampf.mp4"
    </div>

    <div>

        Der Formenlauf, Kombinationen, Übungsfiguren

        Hier ahmst du die Bewegung des Hand- und Fußkampfes gegen einen unsichtbaren (imaginären) Gegner nach
        Du übst die Bewegung in der Gruppe, kämpfst hier nicht gleich gegen einen richtigen Gegner, denn das würde dich beim Lernen neuer Techniken überfordern
        Bei diesem einzigartigen Konzept übst du die gleiche Technik, welche die fortgeschrittenen Sportler ausführen und kannst diese von ihnen nachahmen. Der Meister sieht sofort die kleinsten Fehler und korrigiert sie direkt  – genial, typisch Taekwondo nicht wahr ?
        Du kannst dich nahezu nicht verletzen
        Zunehmend setzt du dich mit mehreren imaginären Gegnern, verschiedenen Angriffs- und Abfangvarianten auseinander
        Die Bewegungen sind in Verlauf, Energie, Endpunkt mit der richtigen Gewichtsverlagerung und exakter Atemkontrolle deines Körpers genauestens festgelegt – Tja, taekwondotypisch ein Höchstmaß ist hier das Geistige Training, die Kontrolle: Ich sage dazu Bewegungsmeditation
        Du schaffst mit diesen Übungen das Fundament, die Grundlage deines Taekwondo; – Tja, du übst dabei: Fleiß, Ausdauer, Genauigkeit, Bescheidenheit, Intensität, Kontrolle, Disziplin und erlernst dabei eine Hingabe, die dich im Leben weiterbringt


    </div>

    <div>
        Wusstest du schon ?

        Du übst alle Bewegung rechts und links gleichermaßen, das schafft einen körperlichen und seelischen Ausgleich
        Du trainierst bei den Taekwondo Übungsformen alle Muskeln – das führt zu einer geraden Körperhaltung, dadurch nimmt deine Umwelt dich ganz anders wahr, das bringt richtig Pluspunkte bei Vorstellungsgesprächen
        Richtiges Atmen schafft in Krisensituationen (Prüfungen, Vortrag) Sicherheit, Stabilität & Konzentration
        Du übst Parallel- und Diagonalbewegungen, das trainiert die rechte und linke Gehirnhälfte – das ist aktives Gehirnjogging
        Bei Verletzungen wirkt sich das Üben von Bewegungsformen positiv auf den Heilungsprozess aus
        Kampfübungen auf einem Bein schaffen ein hohes Gleichgewichtsgefühl und trainieren deine „Feinmuskulatur“

    </div>

</main>




<?php include("Templates/Includes/includesAfterMain.php"); ?>