<?php include("Templates/Includes/includesBeforeMain.php"); ?>

    <main>

    <div class="Video-Säule">
        <video src="/MediaFiles/Videos/UeberUns/Selbstverteidigung.mp4"
    </div>

    <div>

        Sicherheit und Kontrolle

        Hier erlernst du Step by Step die Techniken aus dem Taekwondo & Allkampf in realistischer Anwendung
        Die Tritte, Schläge mit allen Waffen deines Körpers aus dem Taekwondo – die Würfe, Hebel, Festhaltetechniken aus dem Allkampf
        Du wendest die Gegensätze an, z.B. einfach & schwer, groß & klein, schnell & langsam, oben & unten, hart & weich…
        Dein Lernweg fängt mit abgesprochen Angriffen im Einschrittkampf an, mit steigendem Können erlangst du Sicherheit und deine Techniken werden zunehmend schneller, freier und sicherer
        Im Freikampf (im Sparring) lernst du unter Stress richtig zu reagieren, so dass du bestmöglich aus der „Sache“ herauskommst
        Du erlernst in der Selbstbehauptung kommunikativ und strategisch eine gefährliche Situation zu vermeiden, denn der beste Kampf ist der, den man gar nicht erst führen muss!

    </div>

    <div>
        Wusstest du schon ?

        Durch stetiges Trainieren werden deine Sinne geschärft, du nimmst deine Umgebung bewusster wahr
        Selbst in Stress-Situationen und Konflikten reagierst du zunehmend gelassener und behältst einen „kühlen Kopf“
        Im Job und in der Schule, gerade in Prüfungssituationen, steigert sich deine Belastbarkeit
        Die meisten scheitern nicht an guten Techniken, nein, am ungewohnten Stress in einer Kampfsituation, deshalb trainiere bei uns Sparring
        Deine Kicks haben in mittlerer Hüfthöhe die größte Kraft und die weiteste Distanz
    </div>

</main>




<?php include("Templates/Includes/includesAfterMain.php"); ?>