<?php include("Templates/Includes/includesBeforeMain.php"); ?>

    <main>

    <div class="Video-Saeule">
        <video src="/MediaFiles/Videos/UeberUns/Selbstverteidigung.mp4" controls>
            Ihr Browser kann dieses Video leider nicht wiedergeben.<br>
        </video>
    </div>

    <div class="decription_disciplines">

        <h1>Sicherheit und Kontrolle</h1>

        Hier erlernst du Step by Step die Techniken aus dem Taekwondo & Allkampf-Jitsu in realitätsnaher Anwendung.<br>
        Die Tritte und Schläge mit allen Waffen deines Körpers aus dem Taekwondo – die Würfe, Hebel, Festhaltetechniken aus dem Allkampf-Jitsu.<br>
        Du wendest die Gegensätze an, z.B. einfach & schwer, groß & klein, schnell & langsam, oben & unten, hart & weich…<br>
        Dein Lernweg fängt mit abgesprochen Angriffen im Einschrittkampf an, mit steigendem Können erlangst du Sicherheit und deine Techniken werden zunehmend schneller, freier und sicherer<br>
        Im Freikampf lernst du unter Stress richtig zu reagieren, sodass du dich bestmöglich verteidigen kannst.<br>
        Du erlernst in der Selbstbehauptung kommunikativ und strategisch gefährliche Situationen zu vermeiden. Denn der beste Kampf ist der, den man gar nicht erst führen muss!

        <h3>Wusstest du schon?</h3>

        Durch stetiges Trainieren werden deine Sinne geschärft, du nimmst deine Umgebung bewusster wahr.<br>
        Selbst in Stress-Situationen und Konflikten reagierst du zunehmend gelassener und behältst einen „kühlen Kopf“<br>
        Im Job und in der Schule, gerade in Prüfungssituationen, steigert sich deine Belastbarkeit.<br>
        Die meisten scheitern nicht an guten Techniken, sondern daran den Stress in einer Kampfsituation nicht gewohnt zu sein. Deshalb üben wir dies im Freikampf.<br>

    </div>

</main>




<?php include("Templates/Includes/includesAfterMain.php"); ?>