<?php include($_SERVER['DOCUMENT_ROOT']."/Templates/Includes/includesBeforeMain.php"); ?>

<main>
    <div id="ueber_uns_the_beginning">

        <p>
            Seit 2015 wird in Leppersdorf erfolgreicher Sport in der Gemeinde Wachau betrieben.<br>
            Hier engagieren sich Menschen jeden Alters für sportliche Aktivitäten, angefangen bei Kindern ab
            6 Jahren im Kindersport, bis hin zur Jugend und den Erwachsenen.<br>
            Doch das Besondere an unseren sportlichen Angeboten liegt in der Praxis des asiatischen Kampfsports
            Taekwondo.<br>
            Diese Tradition umfasst nicht nur das kraftvolle Kämpfen mit Händen und Füßen zur Selbstverteidigung und
            Selbstbehauptung, sondern auch das Erlernen von defensiven Techniken und Taktiken,
            die auf Aufbau und Stärkung abzielen, anstatt auf Zerstörung. <br>
            <br>
            Die Sportlerinnen und Sportler entwickeln sich ganzheitlich weiter – sowohl körperlich als
            auch geistig, mental und emotional. <br>
            Durch intensive Übungen erlangen sie eine beispiellose körperliche Geschicklichkeit und formen dabei
            ihren Charakter.<br>
            Werte wie Selbstbeherrschung, Konzentration, Durchhaltevermögen, Ausdauer sowie die Überwindung
            von Ängsten werden sowohl den Körper als auch den Geist schulen.<br>
            <br>
            Unsere Mitglieder kommen aus den umliegenden Ortschaften wie Lichtenberg, Lomnitz,
            Seifersdorf, Großröhrsdorf, Pulsnitz, Radeberg, Ullersdorf, Ottendorf und anderen
            Gemeinden, um gemeinsam mit uns in Leppersdorf diesen wunderbaren Sport auszuüben.
        </p>

        <div id="Zeitungsartikel">
            <h2>
                Wie Taekwondo nach Leppersdorf kam
            </h2>
            <p>
                Ein Artikel in der sächsischen Zeitung, von Thomas Drendel.
            </p>
            <p>
                In dem Ort trainieren Dutzende Kinder und Erwachsene koreanischen Kampfsport. Aber
                weshalb?<br>

                Freitagnachmittag in der Leppersdorfer Turnhalle: Gut 30 Mädchen, Jungen und Erwachsene
                in weißen Anzügen und bunten Gürteln springen, laufen und rufen ab und zu koreanische
                Worte. So, als hätten sie nie etwas anderes gemacht. Handball, Fußball oder Gymnastik ok.
                Aber eine koreanische Kampfsportart in einem 1 000 Einwohner-Dorf und der halbe Ort
                macht auch noch mit. Das ist gelinde gesagt, ungewöhnlich und nur einer ganzen Reihe von
                Zufällen zu verdanken.<br>
                <br>
                Die begann vor einigen Jahren mit der Sportbegeisterung von Jochen Klarhöfer. Er hat als
                Kind und Jugendlicher noch in Cottbus Leistungssport betrieben. Leichtathletik vor allem.
                Dabei wurden die Wurzeln gelegt für das, was in Leppersdorf wichtig werden sollte: Ohne
                Sport geht es nicht. Später dann im Beruf als Polizeibeamter kam Jochen Klarhöfer das erste
                Mal mit asiatischer Kampfkunst in Berührung, mit Judo. Klick gemacht hat es aber erst 1996.
                Da begleitete er seinen Sohn zum Training beim Taekwondo Allkampf Club Dresden.
                Während unten im Trainingsraum die Kinder ihre Übungen machten, schaute er von oben zu
                und machte einfach mit. „Ich habe oben das nachgemacht, was mein Sohn und die anderen
                Kinder absolviert haben. Das hat der Trainer gesehen. Beim Verabschieden ließ er keine
                Ausrede gelten und so habe ich meinen Sohn und mich selber angemeldet“, erinnert er sich.<br>
                <br>
                Inzwischen trägt er den Schwarzen Gürtel. Schwarz ist die Farbe der Meister. Sie symbolisiert
                die Autorität, das Wissen und die Erfahrung. Doch ihm geht es nicht um die Farbe. „Es geht
                um den Sport, um das Wissen, was dahinter steckt. Taekwondo ist eine Lebenseinstellung.
                Körperbeherrschung und innere Ausgeglichenheit spielen eine wichtige Rolle.“ Viel habe er
                in dieser Hinsicht von seinem Großmeister Heinrich Magosch an der gleichnamigen
                Sportschule gelernt. Selber zum Meister geworden, machte er dann in Dresden seinen
                Trainerschein. Inzwischen mit seiner Frau nach Leppersdorf gezogen, brachte er seine
                Tochter weiterhin zum Training nach Dresden. Das bekam die Grundschullehrerin in
                Leppersdorf mit und fragte dann, weshalb ich denn nicht hier im Ort Trainingsstunden geben
                würde. Die Grundschule sei auf der Suche nach interessanten Ganztagsangeboten für die
                Kinder. „Mein Arbeitgeber war auch einverstanden, so kam es, dass ich die ersten Stunden
                vor Leppersdorfer Kindern gab“, sagt Jochen Klarhöfer. Als die Mädchen und Jungen dann in
                der vierten Klasse waren, wollten sie natürlich weitermachen. „Ein Club in Dresden war zu
                weit weg. Deshalb blieb nichts anderes übrig, als in Leppersdorf eine Trainingsgruppe zu
                gründen.“ So hat jetzt der Taekwondo Allkampf Club Dresden eine „Abteilung Leppersdorf“.<br>
                <br>
                40 Taekwondo-Begeisterte trainieren hier, die Jüngste ist sieben Jahre alt. Vor jeder
                Trainingseinheit gibt es eine kurze Meditation. Alle reihen sich im Schneidersitz auf. Daumen
                und Zeigefinger aufeinander und innehalten. „Sofort mit den Übungen zu beginnen, das
                würde nicht funktionieren. Dazu sind die Kinder viel zu aufgedreht. Bei der Meditation
                kommen sie zur Ruhe und atmen tief. Das Gehirn wird besser durchblutet. Solche Übungen
                helfen auch in der Schule und im Beruf.“ Dann beginnt das eigentliche Training. Sprünge,
                Läufe und immer wieder bestimmte Bewegungsabläufe: Bein nach vorn, Fauststoß in die
                Luft, den imaginären Gegner mit dem Unterarm blocken – und wieder von vorn. Weshalb
                Kinder wie Erwachsene mit Begeisterung bei der Sache sind? Der Taekwando-Meister kann
                nur mutmaßen. „Wir versuchen, das Training so abwechslungsreich wie möglich zu gestalten.
                Dann machen die Übungen, insbesondere die Selbstverteidigung, selbstbewusster. Außerdem
                haben sie ja auch einige Erfolgserlebnisse.“ Bei Landesmeisterschaften holten beispielsweise
                die Mädchen bereits Gold im Team. Ohne Jochen Klarhöfer wäre es nie dazu gekommen. Das
                sieht auch die Gemeinde Wachau so. Für sein Engagement ist der Leppersdorfer jetzt von der
                Gemeinde ausgezeichnet worden.<br>
                <br>
            </p>
            <p>
                Quelle: Sächsische Zeitung vom 06.02.2018 <br>
                <a href="https://www.saechsische.de/wie-taekwondo-nach-leppersdorf-kam-3873311.html">Original Artikel der Sächsichen Zeitung</a>
            </p>

            <figure class="picture_figure">
                <img src="/MediaFiles/Bilder/UeberUns/Wettkampftraining.webp"
                     alt="Bildbeschreibung">
                <figcaption>© Thorsten Eckert</figcaption>
            </figure>

            <figure class="picture_figure">
                <img src="/MediaFiles/Bilder/UeberUns/Allkampf.webp"
                     alt="Bildbeschreibung">
                <figcaption>Bei Taekwondo-Kämpfen wird der Gegner häufig mit dem Fuß attackiert.<br>
                    © Thorsten Eckert</figcaption>
            </figure>

            <figure class="picture_figure">
                <img src="/MediaFiles/Bilder/UeberUns/Allkmapf_2.webp"
                     alt="Bildbeschreibung">
                <figcaption>Mit Begeisterung sind die jungen Sportler bei der Sache. <br>
                    © Thorsten Eckert</figcaption>
            </figure>

            <figure class="picture_figure">
                <img src="/MediaFiles/Bilder/UeberUns/Gruppenbild.webp"
                     alt="Bildbeschreibung">
                 <figcaption>40 Kinder, Jugendliche und Erwachsene betreiben in Leppersdorf den Sport. <br>
                     © privat</figcaption>
            </figure>


        </div>


    </div>

</main>




<?php include($_SERVER['DOCUMENT_ROOT']."/Templates/Includes/includesAfterMain.php"); ?>