<?php include("Templates/Includes/includesBeforeMain.php"); ?>

    <main>

    <div class="Video-Säule">
        <video src="/MediaFiles/Videos/UeberUns/Wettkampf.mp4"
    </div>

    <div>

        Wettkampf/Sparring – lehrt dich über deine Grenzen zu gehen

        Du kämpfst nach Regeln des olympischen Taekwondo gegen einen Gegner
        Du trägst zum Schutz deiner empfindlichen Körperregionen eine vollständige Schutzausrüstung
        Dein Ziel ist es viele Punkte durch Kicks und deren Kombinationen zu erkämpfen, ohne selbst getroffen zu werden
        Im Wettkampftraining trainierst du deine Ausdauer, Koordination, Schnelligkeit und Dehnfähigkeit
        Dein richtiges Polstertraining führt zu großer Treffsicherheit, enormer Schlagkraft und Schnelligkeit à diese Eigenschaften sind die Basis für effektive Selbstverteidigung und Wettkampf

    </div>

    <div>
        Wusstest du schon ?

        Sparring ist Zweikampf unter hoher psychischer und physischer Hier gewöhnst du dir an, unter Stress mit Verstand zu agieren; – diese „Stress“-Erfahrung helfen dir in der realistischen Selbstverteidigung
        Du willst austeilen, kannst aber auch mal einstecken? Dann ist für dich Wettkampfsport im Taekwondo ideal.
        Du steigerst durch die richtige Technik und dem Wissen von Muskelketten enorm deine Schlagkraft, die Reflexe und die Geschwindigkeit
    </div>

</main>




<?php include("Templates/Includes/includesAfterMain.php"); ?>