<?php include("Templates/Includes/includesBeforeMain.php"); ?>

    <main>

    <div class="Video-Saeule">
        <video src="/MediaFiles/Videos/UeberUns/Wettkampf.mp4" controls>
            Ihr Browser kann dieses Video leider nicht wiedergeben.<br>
        </video>
    </div>

    <div class="decription_disciplines">

        <h1>Wettkampf / Sparring </h1>

        Lehrt dich über deine Grenzen zu gehen.<br>
        Du kämpfst nach Regeln des olympischen Taekwondo gegen einen Gegner.<br>
        Du trägst zum Schutz deiner empfindlichen Körperregionen eine vollständige Schutzausrüstung.<br>
        Dein Ziel ist es viele Punkte durch Kicks und deren Kombinationen zu erkämpfen, ohne selbst getroffen zu werden.<br>
        Im Wettkampftraining trainierst du deine Ausdauer, Koordination, Schnelligkeit und Dehnfähigkeit.<br>
        Das richtige Polstertraining führt zu großer Treffsicherheit, enormer Schlagkraft und Schnelligkeit, all diese Eigenschaften sind die Basis für effektive Selbstverteidigung und Wettkampf.<br>

        <h3>Wusstest du schon?</h3>

        Sparring ist Zweikampf unter hoher psychischer und physischer Last. Hier gewöhnst du dir an, unter Stress mit Verstand zu agieren; – diese „Stress“-Erfahrung helfen dir in der realistischen Selbstverteidigung.<br>
        Du willst austeilen, kannst aber auch mal einstecken? Dann ist für dich Wettkampfsport im Taekwondo ideal.<br>
        Du steigerst, durch die richtige Technik und dem Wissen von Muskelketten, enorm deine Schlagkraft, die Reflexe und die Geschwindigkeit.<br>
    </div>

</main>




<?php include("Templates/Includes/includesAfterMain.php"); ?>