<?php include("Templates/Includes/includesBeforeMain.php"); ?>

    <main>

    <div class="Video-Saeule">
        <video src="/MediaFiles/Videos/UeberUns/Workout.mp4" controls>
            Ihr Browser kann dieses Video leider nicht wiedergeben.<br>
        </video>
    </div>

    <div class="decription_disciplines">

        <h1>Workouts</h1>

        Bringen dir Power und machen dich fit.<br>
        Du übst Schlagtechniken, mit der Faust, mit der Handkante, mit dem Ellenbogen – verbunden mit bekannten Workout-Übungen.<br>
        Du steigerst durch die richtige Technik und dem Wissen von Muskelketten enorm deine Schlagkraft, die Reflexe und die Geschwindigkeit.<br>
        Du trainierst beim Kicktraining paarweise oder in Gruppe, durch „Reaktionsspiele“ Musik, Rhythmus ist der Spaßfaktor garantiert.<br>
        Du powerst dich beim Überwinden über unseren Parcours mit Koordinationsleiter, Pylonen, Matten, Standboxsack usw. aus.<br>

        <h3>Wusstest du schon?</h3>

        Dass zweimal in der Woche 30 Minuten intensive Workouts zu den gleichen Ergebnissen führen, wie 3x wöchentlich 60 Minuten laufen?
        Du „verbrennst“ selbst Stunden nach dem Training noch Kalorien, auch wenn du bereits auf der Couch sitzt.<br>
        Nach intensiven Übungen fühlt sich der Körper richtig stark; neulich sagte mir eine Sportlerin „Mann oh Mann jetzt habe ich wieder den Kopf frei, Danke!“<br>
        Du trainierst mit anderen und lernst diese kennen, das motiviert dich.<br>
        Die Übungen sind sehr abwechslungsreich, da kommt keine „Langeweile“ auf.<br>
        Im Taekwondo sind in die Workout-Übungen Block, Schlag und Tritt-Bewegungen eingebaut, da hat das Ganze noch einen höheren Wert.<br>
        Du förderst das Muskelwachstum, das ist die Stütze der Knochen schlechthin, das beugt z.B. Rückschmerzen vor und es behebt mit der Zeit vorhandene Dysbalancen.<br>
        Stretching und aktive Dehnung erhöht den Bewegungsumfang der Gelenke.<br>
        Es gibt sogar ein Taekwondo-Sportabzeichen, das kann in Gold, Silber oder Bronze ablegen und kann als Teildisziplin für das deutsche Sportabzeichen eingesetzt werden.
    </div>

</main>




<?php include("Templates/Includes/includesAfterMain.php"); ?>