<?php include("Templates/Includes/includesBeforeMain.php"); ?>

    <main>

    <div class="Video-Säule">
        <video src="/MediaFiles/Videos/UeberUns/Workout.mp4"
    </div>

    <div>

        Workouts – bringen dir Power und machen dich fit

        Du übst Schlagtechniken, mit der Faust, mit der Handkante, mit dem Ellenbogen – verbunden mit bekannten Workout-Übungen
        Du steigerst durch die richtige Technik und dem Wissen von Muskelketten enorm deine Schlagkraft, die Reflexe und die Geschwindigkeit
        Du trainierst beim Kicktraining paarweise oder in Gruppe, durch „Reaktionsspiele“ Musik, Rhythmus ist der Spaßfaktor garantiert
        Deine Kicks haben in mittlerer Hüfthöhe die größte Kraft und die weiteste Distanz
        Dein richtiges Polstertraining führt zu großer Treffsicherheit, enormer Schlagkraft, Schnelligkeit à diese Eigenschaften sind die Basis für effektive Selbstverteidigung und Wettkampf
        Du powerst dich beim Überwinden über unseren Parcours mit Koordinationsleiter, Pylonen, Matten, Standboxsack usw. aus

    </div>

    <div>
        Wusstest du schon ?

        Das zweimal in der Woche 30 Minuten intensive Workouts zu den gleichen Ergebnissen führen, wie 3x wöchentlich 60 Minuten laufen à kostet also wenig Zeit
        Du „verbrennst“ selbst Stunden nach dem Training noch Kalorien, wenn du auf der Couch sitzt
        Nach intensiven Übungen fühlt sich der Körper richtig stark; neulich sagte mir eine Sportlerin „Mann oh Mann jetzt habe ich wieder den Kopf frei, Danke !“
        Du trainierst mit anderen und lernst diese kennen, das motiviert dich
        Die Übungen sind irre abwechslungsreich, da kommt keine „Langeweile“ auf
        Im Taekwondo sind in die Workout-Übungen Block, Schlag und Tritt-Bewegungen eingebaut, da hat das Ganze noch einen höheren Wert
        Du förderst das Muskelwachstum, das ist die Stütze der Knochen schlechthin, das beugt z.B. Rückschmerzen vor à es behebt mit der Zeit Dysbalancen
        Stretching und aktive Dehnung erhöht dein Bewegungsumfang der Gelenke
        Das Taekwondo-Sportabzeichen kannst du hier in Gold, Silber oder Bronze ablegen
    </div>

</main>




<?php include("Templates/Includes/includesAfterMain.php"); ?>