version: "3"

services:
  apache:
    image: webdevops/apache:latest
    container_name: "udemy-apache"
    environment:
      - WEB_PHP_SOCKET=php:9000
    volumes:
      - ..:/app
    ports:
      - "8080:443"

  php:
    container_name: "udemy-php"
    volumes:
      - ..:/app
    build:
      context: ./php

  mySql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
#    restart: always
    container_name: "udemy-mySql"
    ports:
      - "33306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=testroot
      - MYSQL_DATABASE=testdatabase
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testpassword
    volumes:
      - ./mySql/data:/var/lib/mysql

