<?php include("Includes/includesBeforeMain.php"); ?>

<main>
    <div class="Datenschutzerklaerung">
        <h1>Datenschutzerkl&auml;rung</h1>

        <h2>1) Einleitung und Kontaktdaten des Verantwortlichen</h2>

        <p><b>1.1</b>&nbsp;Wir freuen uns, dass Sie unsere Website besuchen und bedanken uns f&uuml;r Ihr Interesse. Im Folgenden informieren wir Sie &uuml;ber den Umgang mit Ihren personenbezogenen Daten bei der Nutzung unserer Website. Personenbezogene Daten sind hierbei alle Daten, mit denen Sie pers&ouml;nlich identifiziert werden k&ouml;nnen.</p>

        <p><b>1.2</b>&nbsp;Verantwortlicher f&uuml;r die Datenverarbeitung auf dieser Website im Sinne der Datenschutz-Grundverordnung (DSGVO) ist Taekwondo- Allkampfclub Dresden e.V., Am Dreieck 3, 01454 Leppersdorf, Deutschland, Tel.: 01727592402, E-Mail: info@taekwondo-allkampf-leppersdorf.de. Der f&uuml;r die Verarbeitung von personenbezogenen Daten Verantwortliche ist diejenige nat&uuml;rliche oder juristische Person, die allein oder gemeinsam mit anderen &uuml;ber die Zwecke und Mittel der Verarbeitung von personenbezogenen Daten entscheidet.</p>

        <h2>2) Datenerfassung beim Besuch unserer Website</h2>

        <p><b>2.1</b>&nbsp;Bei der blo&szlig; informatorischen Nutzung unserer Website, also wenn Sie sich nicht registrieren oder uns anderweitig Informationen &uuml;bermitteln, erheben wir nur solche Daten, die Ihr Browser an den Seitenserver &uuml;bermittelt (sog. &bdquo;Server-Logfiles&#8220;). Wenn Sie unsere Website aufrufen, erheben wir die folgenden Daten, die f&uuml;r uns technisch erforderlich sind, um Ihnen die Website anzuzeigen:</p>

        <ul>
            <li>Unsere besuchte Website</li>
            <li>Datum und Uhrzeit zum Zeitpunkt des Zugriffes</li>
            <li>Menge der gesendeten Daten in Byte</li>
            <li>Quelle/Verweis, von welchem Sie auf die Seite gelangten</li>
            <li>Verwendeter Browser</li>
            <li>Verwendetes Betriebssystem</li>
            <li>Verwendete IP-Adresse (ggf.: in anonymisierter Form)</li>
        </ul>

        <p>Die Verarbeitung erfolgt gem&auml;&szlig; Art. 6 Abs. 1 lit. f DSGVO auf Basis unseres berechtigten Interesses an der Verbesserung der Stabilit&auml;t und Funktionalit&auml;t unserer Website. Eine Weitergabe oder anderweitige Verwendung der Daten findet nicht statt. Wir behalten uns allerdings vor, die Server-Logfiles nachtr&auml;glich zu &uuml;berpr&uuml;fen, sollten konkrete Anhaltspunkte auf eine rechtswidrige Nutzung hinweisen.</p>

        <p><b>2.2</b>&nbsp;Diese Website nutzt aus Sicherheitsgr&uuml;nden und zum Schutz der &Uuml;bertragung personenbezogener Daten und anderer vertraulicher Inhalte (z.B. Bestellungen oder Anfragen an den Verantwortlichen) eine SSL-bzw. TLS-Verschl&uuml;sselung. Sie k&ouml;nnen eine verschl&uuml;sselte Verbindung an der Zeichenfolge &bdquo;https://&#8220; und dem Schloss-Symbol in Ihrer Browserzeile erkennen.</p>

        <h2>3) Cookies</h2>

        <p>Um den Besuch unserer Website attraktiv zu gestalten und die Nutzung bestimmter Funktionen zu erm&ouml;glichen, verwenden wir Cookies, also kleine Textdateien, die auf Ihrem Endger&auml;t abgelegt werden. Teilweise werden diese Cookies nach Schlie&szlig;en des Browsers automatisch wieder gel&ouml;scht (sog. &bdquo;Session-Cookies&#8220;), teilweise verbleiben diese Cookies l&auml;nger auf Ihrem Endger&auml;t und erm&ouml;glichen das Speichern von Seiteneinstellungen (sog. &bdquo;persistente Cookies&#8220;). Im letzteren Fall k&ouml;nnen Sie die Speicherdauer der &Uuml;bersicht zu den Cookie-Einstellungen Ihres Webbrowsers entnehmen.</p>

        <p>Sofern durch einzelne von uns eingesetzte Cookies auch personenbezogene Daten verarbeitet werden, erfolgt die Verarbeitung gem&auml;&szlig; Art. 6 Abs. 1 lit. b DSGVO entweder zur Durchf&uuml;hrung des Vertrages, gem&auml;&szlig; Art. 6 Abs. 1 lit. a DSGVO im Falle einer erteilten Einwilligung oder gem&auml;&szlig; Art. 6 Abs. 1 lit. f DSGVO zur Wahrung unserer berechtigten Interessen an der bestm&ouml;glichen Funktionalit&auml;t der Website sowie einer kundenfreundlichen und effektiven Ausgestaltung des Seitenbesuchs.</p>

        <p>Sie k&ouml;nnen Ihren Browser so einstellen, dass Sie &uuml;ber das Setzen von Cookies informiert werden und einzeln &uuml;ber deren Annahme entscheiden oder die Annahme von Cookies f&uuml;r bestimmte F&auml;lle oder generell ausschlie&szlig;en k&ouml;nnen.</p>

        <p>Bitte beachten Sie, dass bei Nichtannahme von Cookies die Funktionalit&auml;t unserer Website eingeschr&auml;nkt sein kann.</p>

        <h2>4) Kontaktaufnahme</h2>

        <p>Im Rahmen der Kontaktaufnahme mit uns (z.B. per Kontaktformular oder E-Mail) werden personenbezogene Daten erhoben. Welche Daten im Falle der Nutzung eines Kontaktformulars erhoben werden, ist aus dem jeweiligen Kontaktformular ersichtlich. Diese Daten werden ausschlie&szlig;lich zum Zweck der Beantwortung Ihres Anliegens bzw. f&uuml;r die Kontaktaufnahme und die damit verbundene technische Administration gespeichert und verwendet.</p>

        <p>Rechtsgrundlage f&uuml;r die Verarbeitung dieser Daten ist unser berechtigtes Interesse an der Beantwortung Ihres Anliegens gem&auml;&szlig; Art. 6 Abs. 1 lit. f DSGVO. Zielt Ihre Kontaktierung auf den Abschluss eines Vertrages ab, so ist zus&auml;tzliche Rechtsgrundlage f&uuml;r die Verarbeitung Art. 6 Abs. 1 lit. b DSGVO. Ihre Daten werden nach abschlie&szlig;ender Bearbeitung Ihrer Anfrage gel&ouml;scht. Dies ist der Fall, wenn sich aus den Umst&auml;nden entnehmen l&auml;sst, dass der betroffene Sachverhalt abschlie&szlig;end gekl&auml;rt ist und sofern keine gesetzlichen Aufbewahrungspflichten entgegenstehen.</p>

        <h2>5) Registrierung beim Portal bzw. Forum</h2>

        <p>Sie k&ouml;nnen sich auf unserer Website unter Angabe von personenbezogenen Daten registrieren. Welche personenbezogenen Daten f&uuml;r die Registrierung verarbeitet werden, ergibt sich aus der Eingabemaske, die f&uuml;r die Registrierung verwendet wird. Wir verwenden f&uuml;r die Registrierung das sog. Double-opt-in-Verfahren, d.&ThinSpace;h. Ihre Registrierung ist erst abgeschlossen, wenn Sie zuvor Ihre Anmeldung &uuml;ber eine Ihnen zu diesem Zweck zugesandte Best&auml;tigungs-E-Mail durch Klick auf den darin enthaltenem Link best&auml;tigt haben. Falls Ihre diesbez&uuml;gliche Best&auml;tigung nicht binnen 24 Stunden erfolgt, wird Ihre Anmeldung automatisch aus unserer Datenbank gel&ouml;scht. Die Angabe der zuvor genannten Daten ist verpflichtend. Alle weiteren Informationen k&ouml;nnen Sie freiwillig durch Nutzung unseres Portals bereitstellen.</p>

        <p>Wenn Sie unser Portal nutzen, speichern wir Ihre zur Vertragserf&uuml;llung erforderlichen Daten, auch evtl. Angaben zur Zahlungsweise, bis Sie Ihren Zugang endg&uuml;ltig l&ouml;schen. Weiterhin speichern wir die von Ihnen angegebenen freiwilligen Daten f&uuml;r die Zeit Ihrer Nutzung des Portals, soweit Sie diese nicht zuvor l&ouml;schen. Alle Angaben k&ouml;nnen Sie im gesch&uuml;tzten Kundenbereich verwalten und &auml;ndern. Rechtsgrundlage ist Art. 6 Abs. 1 lit. f DSGVO.</p>

        <p>Dar&uuml;ber hinaus speichern wir alle von Ihnen ver&ouml;ffentlichten Inhalte (wie z.B. &ouml;ffentliche Beitr&auml;ge, Pinnwandeintr&auml;ge, G&auml;stebucheintragungen, etc.), um die Website zu betreiben. Wir haben ein berechtigtes Interesse an der Bereitstellung der Website mit dem vollst&auml;ndigen User-Generated-Content. Die Rechtsgrundlage hierf&uuml;r ist Art. 6 Abs. 1 lit. f DSGVO. Wenn Sie Ihren Account l&ouml;schen, bleiben Ihre &ouml;ffentlichen &Auml;u&szlig;erungen, insbesondere im Forum, weiterhin f&uuml;r alle Leser sichtbar, Ihr Account ist jedoch nicht mehr abrufbar. Alle &uuml;brigen Daten werden in diesem Fall gel&ouml;scht.</p>

        <h2>6) Seitenfunktionalit&auml;ten</h2>

        <p>Google Maps</p>

        <p>Diese Webseite nutzt einen Online-Kartendienst des folgenden Anbieters: Google Maps (API) von Google Ireland Limited, Gordon House, 4 Barrow St, Dublin, D04 E5W5, Irland (&#8220;Google&rdquo;).</p>

        <p>Google Maps ist ein Webdienst zur Darstellung von interaktiven (Land-)Karten, um geographische Informationen visuell darzustellen. &Uuml;ber die Nutzung dieses Dienstes wird Ihnen unser Standort angezeigt und eine etwaige Anfahrt erleichtert.</p>

        <p>Bereits beim Aufrufen derjenigen Unterseiten, in die die Karte von Google Maps eingebunden ist, werden Informationen &uuml;ber Ihre Nutzung unserer Website (wie z.B. Ihre IP-Adresse) an Server von Google &uuml;bertragen und dort gespeichert, hierbei kann es auch zu einer &Uuml;bermittlung an die Server der Google LLC. in den USA kommen. Dies erfolgt unabh&auml;ngig davon, ob Google ein Nutzerkonto bereitstellt, &uuml;ber das Sie eingeloggt sind oder ob ein Nutzerkonto besteht. Wenn Sie bei Google eingeloggt sind, werden Ihre Daten direkt Ihrem Konto zugeordnet. Wenn Sie die Zuordnung mit Ihrem Profil bei Google nicht w&uuml;nschen, m&uuml;ssen Sie sich vor Aktivierung des Buttons ausloggen. Google speichert Ihre Daten (selbst f&uuml;r nicht eingeloggte Nutzer) als Nutzungsprofile und wertet diese aus.</p>

        <p>Die Erhebung, Speicherung und die Auswertung erfolgen gem&auml;&szlig; Art. 6 Abs. 1 lit. f DSGVO auf Basis des berechtigten Interesses von Google an der Einblendung personalisierter Werbung, Marktforschung und/oder der bedarfsgerechten Gestaltung von Google-Websites. Ihnen steht ein Widerspruchsrecht gegen die Bildung dieser Nutzerprofile zu, wobei Sie sich f&uuml;r dessen Aus&uuml;bung an Google wenden m&uuml;ssen. Wenn Sie mit der k&uuml;nftigen &Uuml;bermittlung Ihrer Daten an Google im Rahmen der Nutzung von Google Maps nicht einverstanden sind, besteht auch die M&ouml;glichkeit, den Webdienst von Google Maps vollst&auml;ndig zu deaktivieren, indem Sie die Anwendung JavaScript in Ihrem Browser ausschalten. Google Maps und damit auch die Kartenanzeige auf dieser Internetseite kann dann nicht genutzt werden.</p>

        <p>Soweit rechtlich erforderlich, haben wir zur vorstehend dargestellten Verarbeitung Ihrer Daten Ihre Einwilligung gem&auml;&szlig; Art. 6 Abs. 1 lit. a DSGVO eingeholt. Sie k&ouml;nnen Ihre erteilte Einwilligung jederzeit mit Wirkung f&uuml;r die Zukunft widerrufen. Um Ihren Widerruf auszu&uuml;ben, befolgen Sie bitte die vorstehend geschilderte M&ouml;glichkeit zur Vornahme eines Widerspruchs.</p>

        <p>F&uuml;r Daten&uuml;bermittlungen in die USA hat sich der Anbieter dem EU-US-Datenschutzrahmen (EU-US Data Privacy Framework) angeschlossen, das auf Basis eines Angemessenheitsbeschlusses der Europ&auml;ischen Kommission die Einhaltung des europ&auml;ischen Datenschutzniveaus sicherstellt.</p>

        <h2>7) Tools und Sonstiges</h2>

        <p>Cookie-Consent-Tool</p>

        <p>Diese Website nutzt zur Einholung wirksamer Nutzereinwilligungen f&uuml;r einwilligungspflichtige Cookies und cookie-basierte Anwendungen ein sog. &bdquo;Cookie-Consent-Tool&#8220;. Das &bdquo;Cookie-Consent-Tool&#8220; wird Nutzern bei Seitenaufruf in Form einer interaktive Benutzeroberfl&auml;che angezeigt, auf welcher sich per H&auml;kchensetzung Einwilligungen f&uuml;r bestimmte Cookies und/oder cookie-basierte Anwendungen erteilen lassen. Hierbei werden durch den Einsatz des Tools alle einwilligungspflichtigen Cookies/Dienste nur dann geladen, wenn der jeweilige Nutzer entsprechende Einwilligungen per H&auml;kchensetzung erteilt. So wird sichergestellt, dass nur im Falle einer erteilten Einwilligung derartige Cookies auf dem jeweiligen Endger&auml;t des Nutzers gesetzt werden.</p>

        <p>Das Tool setzt technisch notwendige Cookies, um Ihre Cookie-Pr&auml;ferenzen zu speichern. Personenbezogene Nutzerdaten werden hierbei grunds&auml;tzlich nicht verarbeitet.</p>

        <p>Kommt es im Einzelfall zum Zwecke der Speicherung, Zuordnung oder Protokollierung von Cookie-Einstellungen doch zur Verarbeitung personenbezogener Daten (wie etwa der IP-Adresse), erfolgt diese gem&auml;&szlig; Art. 6 Abs. 1 lit. f DSGVO auf Basis unseres berechtigten Interesses an einem rechtskonformen, nutzerspezifischen und nutzerfreundlichen Einwilligungsmanagement f&uuml;r Cookies und mithin an einer rechtskonformen Ausgestaltung unseres Internetauftritts.</p>

        <p>Weitere Rechtsgrundlage f&uuml;r die Verarbeitung ist ferner Art. 6 Abs. 1 lit. c DSGVO. Wir unterliegen als Verantwortliche der rechtlichen Verpflichtung, den Einsatz technisch nicht notwendiger Cookies von der jeweiligen Nutzereinwilligung abh&auml;ngig zu machen.</p>

        <p>Soweit erforderlich, haben wir mit dem Anbieter einen Auftragsverarbeitungsvertrag geschlossen, der den Schutz der Daten unserer Seitenbesucher sicherstellt und eine unberechtigte Weitergabe an Dritte untersagt.</p>

        <p>Weitere Informationen zum Betreiber und den Einstellungsm&ouml;glichkeiten des Cookie-Consent-Tools finden Sie direkt in der entsprechenden Benutzeroberfl&auml;che auf unserer Website.</p>

        <h2>8) Rechte des Betroffenen</h2>

        <p><b>8.1</b>&nbsp;Das geltende Datenschutzrecht gew&auml;hrt Ihnen gegen&uuml;ber dem Verantwortlichen hinsichtlich der Verarbeitung Ihrer personenbezogenen Daten die nachstehenden Betroffenenrechte (Auskunfts- und Interventionsrechte), wobei f&uuml;r die jeweiligen Aus&uuml;bungsvoraussetzungen auf die angef&uuml;hrte Rechtsgrundlage verwiesen wird:</p>

        <ul>
            <li>Auskunftsrecht gem&auml;&szlig; Art. 15 DSGVO;</li>
            <li>Recht auf Berichtigung gem&auml;&szlig; Art. 16 DSGVO;</li>
            <li>Recht auf L&ouml;schung gem&auml;&szlig; Art. 17 DSGVO;</li>
            <li>Recht auf Einschr&auml;nkung der Verarbeitung gem&auml;&szlig; Art. 18 DSGVO;</li>
            <li>Recht auf Unterrichtung gem&auml;&szlig; Art. 19 DSGVO;</li>
            <li>Recht auf Daten&uuml;bertragbarkeit gem&auml;&szlig; Art. 20 DSGVO;</li>
            <li>Recht auf Widerruf erteilter Einwilligungen gem&auml;&szlig; Art. 7 Abs. 3 DSGVO;</li>
            <li>Recht auf Beschwerde gem&auml;&szlig; Art. 77 DSGVO.</li>
        </ul>

        <p><b>8.2</b>&nbsp;WIDERSPRUCHSRECHT</p>

        <p>WENN WIR IM RAHMEN EINER INTERESSENABW&Auml;GUNG IHRE PERSONENBEZOGENEN DATEN AUFGRUND UNSERES &Uuml;BERWIEGENDEN BERECHTIGTEN INTERESSES VERARBEITEN, HABEN SIE DAS JEDERZEITIGE RECHT, AUS GR&Uuml;NDEN, DIE SICH AUS IHRER BESONDEREN SITUATION ERGEBEN, GEGEN DIESE VERARBEITUNG WIDERSPRUCH MIT WIRKUNG F&Uuml;R DIE ZUKUNFT EINZULEGEN.</p>

        <p>MACHEN SIE VON IHREM WIDERSPRUCHSRECHT GEBRAUCH, BEENDEN WIR DIE VERARBEITUNG DER BETROFFENEN DATEN. EINE WEITERVERARBEITUNG BLEIBT ABER VORBEHALTEN, WENN WIR ZWINGENDE SCHUTZW&Uuml;RDIGE GR&Uuml;NDE F&Uuml;R DIE VERARBEITUNG NACHWEISEN K&Ouml;NNEN, DIE IHRE INTERESSEN, GRUNDRECHTE UND GRUNDFREIHEITEN &Uuml;BERWIEGEN, ODER WENN DIE VERARBEITUNG DER GELTENDMACHUNG, AUS&Uuml;BUNG ODER VERTEIDIGUNG VON RECHTSANSPR&Uuml;CHEN DIENT.</p>

        <p>WERDEN IHRE PERSONENBEZOGENEN DATEN VON UNS VERARBEITET, UM DIREKTWERBUNG ZU BETREIBEN, HABEN SIE DAS RECHT, JEDERZEIT WIDERSPRUCH GEGEN DIE VERARBEITUNG SIE BETREFFENDER PERSONENBEZOGENER DATEN ZUM ZWECKE DERARTIGER WERBUNG EINZULEGEN. SIE K&Ouml;NNEN DEN WIDERSPRUCH WIE OBEN BESCHRIEBEN AUS&Uuml;BEN.</p>

        <p>MACHEN SIE VON IHREM WIDERSPRUCHSRECHT GEBRAUCH, BEENDEN WIR DIE VERARBEITUNG DER BETROFFENEN DATEN ZU DIREKTWERBEZWECKEN.</p>

        <h2>9) Dauer der Speicherung personenbezogener Daten</h2>

        <p>Die Dauer der Speicherung von personenbezogenen Daten bemisst sich anhand der jeweiligen Rechtsgrundlage, am Verarbeitungszweck und &ndash; sofern einschl&auml;gig &ndash; zus&auml;tzlich anhand der jeweiligen gesetzlichen Aufbewahrungsfrist (z.B. handels- und steuerrechtliche Aufbewahrungsfristen).</p>

        <p>Bei der Verarbeitung von personenbezogenen Daten auf Grundlage einer ausdr&uuml;cklichen Einwilligung gem&auml;&szlig; Art. 6 Abs. 1 lit. a DSGVO werden die betroffenen Daten so lange gespeichert, bis Sie Ihre Einwilligung widerrufen.</p>

        <p>Existieren gesetzliche Aufbewahrungsfristen f&uuml;r Daten, die im Rahmen rechtsgesch&auml;ftlicher bzw. rechtsgesch&auml;fts&auml;hnlicher Verpflichtungen auf der Grundlage von Art. 6 Abs. 1 lit. b DSGVO verarbeitet werden, werden diese Daten nach Ablauf der Aufbewahrungsfristen routinem&auml;&szlig;ig gel&ouml;scht, sofern sie nicht mehr zur Vertragserf&uuml;llung oder Vertragsanbahnung erforderlich sind und/oder unsererseits kein berechtigtes Interesse an der Weiterspeicherung fortbesteht.</p>

        <p>Bei der Verarbeitung von personenbezogenen Daten auf Grundlage von Art. 6 Abs. 1 lit. f DSGVO werden diese Daten so lange gespeichert, bis Sie Ihr Widerspruchsrecht nach Art. 21 Abs. 1 DSGVO aus&uuml;ben, es sei denn, wir k&ouml;nnen zwingende schutzw&uuml;rdige Gr&uuml;nde f&uuml;r die Verarbeitung nachweisen, die Ihre Interessen, Rechte und Freiheiten &uuml;berwiegen, oder die Verarbeitung dient der Geltendmachung, Aus&uuml;bung oder Verteidigung von Rechtsanspr&uuml;chen.</p>

        <p>Bei der Verarbeitung von personenbezogenen Daten zum Zwecke der Direktwerbung auf Grundlage von Art. 6 Abs. 1 lit. f DSGVO werden diese Daten so lange gespeichert, bis Sie Ihr Widerspruchsrecht nach Art. 21 Abs. 2 DSGVO aus&uuml;ben.</p>

        <p>Sofern sich aus den sonstigen Informationen dieser Erkl&auml;rung &uuml;ber spezifische Verarbeitungssituationen nichts anderes ergibt, werden gespeicherte personenbezogene Daten im &Uuml;brigen dann gel&ouml;scht, wenn sie f&uuml;r die Zwecke, f&uuml;r die sie erhoben oder auf sonstige Weise verarbeitet wurden, nicht mehr notwendig sind.</p>
    </div>
</main>




<?php include("Includes/includesAfterMain.php"); ?>