<?php include("Includes/includesBeforeMain.php"); ?>

    <main>
        <div>
            <h1>Terminkalender</h1>
        </div>
        <br>

        <div <div class="Events_Overview">
            <div class="Events_Overview_Year">
                <h2>
                    <?php $thisYear = date("Y");
                        echo $thisYear; ?>
                </h2>
            </div>

            <?php
                if ($events == []):
            ?>
                <div>
                    <h2>
                        Ein Fehler ist aufgetreten.
                    </h2>
                </div>
            <?php
                endif;
            ?>

            <?php foreach ($events as $event):
                if ($event->getEventYear() == $thisYear) {
            ?>
                <div class="Events_Overview_Table">

                    <div class="Events_Overview_Date">
                        <?= $event->getDate(); ?>
                    </div>

                    <div class="Events_Overview_Headline">
                        <?= $event->getName(); ?>
                    </div>

                    <div class="Events_Overview_Details">
                        <a href="<?php echo App::getBaseURL() ?>termine/details/id/<?php echo $event->getId() ?>">Details</a>
                    </div>

                    <?php if($canEdit): ?>
                        <div id="Events_Overview_Delete">
                            <a href="<?php echo App::getBaseURL() ?>termine/delete/id/<?php echo $event->getId() ?>">löschen</a>
                        </div>
                    <?php endif; ?>

                </div>
                <hr>

            <?php };endforeach; ?>

        </div>

        <br>

        <div class="Events_Overview">
            <div class="Events_Overview_Year">
                <h2>
                    <?php $nextYear = date("Y") +1;
                    echo $nextYear; ?>
                </h2>
            </div>

            <?php foreach ($events as $event):
                if ($event->getEventYear() == $nextYear) {
            ?>
                <div class="Events_Overview_Table">

                    <div class="Events_Overview_Date">
                        <?= $event->getDate(); ?>
                    </div>

                    <div class="Events_Overview_Headline">
                        <?= $event->getName(); ?>
                    </div>

                    <div class="Events_Overview_Details">
                        <a href="<?php echo App::getBaseURL() ?>termine/details/id/<?php echo $event->getId() ?>">Details</a>
                    </div>

                    <?php if($canEdit): ?>
                        <div id="Events_Overview_Delete">
                            <a href="<?php echo App::getBaseURL() ?>termine/delete/id/<?php echo $event->getId() ?>">löschen</a>
                        </div>
                    <?php endif; ?>


                </div>
                <hr>

            <?php };endforeach; ?>

        </div>

        <?php if($canEdit): ?>

        <h3>Neuen Termin erstellen:</h3>
        <div class="Formular">
            <form method="post" class="event-formular" enctype="multipart/form-data">

                <label for="date">Datum:</label><br>
                <input type="date" id="date" name="date" required><br>

                <label for="name">Name:</label><br>
                <input type="text" id="name" name="name" required><br>

                <label for="description">Beschreibung:</label><br>
                <textarea id="description" name="description" cols="30" rows="5" wrap="soft" required></textarea><br>

                <label for="file1">Dateien:</label><br>
                <input name="file[]" type="file" multiple id="file1" accept="application/pdf,image/jpeg,image/png"><br>

                <div class="Formular_Submit">
                    <input type="submit" value="Submit">
                </div>

            </form>
        </div>

        <?php endif; ?>



    </main>

<?php include("Includes/includesAfterMain.php"); ?>