<?php include("Includes/includesBeforeMain.php"); ?>

    <main>
        <div>
            <h1>Terminkalender</h1>
        </div>

        <div>
            <div class="Events_Overview_Year">
                <h2>
                    <?php $thisYear = date("Y");
                        echo $thisYear; ?>
                </h2>
            </div>

            <?php foreach ($events as $event):
                if ($event->getEventYear() == $thisYear) {
            ?>
                <div class="Events_Overview_Table">

                    <div class="Events_Overview_Date">
                        <?= $event->getDate(); ?>
                    </div>

                    <div class="Events_Overview_Headline">
                        <?= $event->getName(); ?>
                    </div>

                    <div class="Events_Overview_Details">
                        <a href="<?php echo App::getBaseURL() ?>termine/details/id/<?php echo $event->getId() ?>">Details</a>
                    </div>
                </div>
                <hr>

            <?php };endforeach; ?>

        </div>

        <div>
            <div class="Events_Overview_Year">
                <h2>
                    <?php $nextYear = date("Y") +1;
                    echo $nextYear; ?>
                </h2>
            </div>

            <?php foreach ($events as $event):
                if ($event->getEventYear() == $nextYear) {
            ?>
                <div class="Events_Overview_Table">

                    <div class="Events_Overview_Date">
                        <?= $event->getDate(); ?>
                    </div>

                    <div class="Events_Overview_Headline">
                        <?= $event->getName(); ?>
                    </div>

                    <div class="Events_Overview_Details">
                        <a href="<?php echo App::getBaseURL() ?>termine/details/id/<?php echo $event->getId() ?>">Details</a>
                    </div>
                </div>
                <hr>

            <?php };endforeach; ?>

        </div>

        <?php if($canEdit): ?>

        <div>
            <form method="post" class="event-formular" enctype="multipart/form-data">

                <label for="date">Datum:</label><br>
                <input type="date" id="date" name="date" required><br>

                <label for="name">Name:</label><br>
                <input type="text" id="name" name="name" required><br>

                <label for="description">Beschreibung:</label><br>
                <input type="text" id="description" name="description" required><br>

                <label for="file1">Dateien:</label><br>
                <input name="file[]" type="file" multiple id="file1" accept="application/pdf,image/jpeg,image/png"><br>

                <button type="submit">Termin erstellen</button>

            </form>
        </div>

        <?php endif; ?>



    </main>

<?php include("Includes/includesAfterMain.php"); ?>