<?php include("Includes/includesBeforeMain.php"); ?>

    <main>

        <div class="Events_Details_Headline">
            <h2>
                <?php echo $events['name']; ?>
            </h2>
        </div>

        <div>
            <h3>
                <?php echo $events['date']; ?>
            </h3>
        </div>


        <div class="Events_Details_Decription">
            <?php echo $events['description']; ?>
        </div>

        <h2>Dokumente:</h2>

        <?php foreach ($events['documents'] as $file): ?>
            <div class="Events_Details_Documents">
                <?php
                    $filename = $file['filename'];
                    $id = $file['id'];
                ?>

                <div id="Events_Deatails_Documents_Document">
                    <a href="<?php echo App::getBaseURL()."temp/". $filename; ?>"><?php echo $filename; ?></a>
                </div>
                <?php if($canEdit): ?>
                    <div id="Events_Deatails_Documents_Delete">
                        <a href="<?php echo App::getBaseURL() ?>termine/deleteDocument/fileid/<?php echo $id; ?>/eventid/<?php echo $events['eventID']; ?>">löschen</a>
                    </div>
                 <?php endif; ?>
            </div>
        <?php endforeach; ?>



        <?php if($canEdit): ?>

            <hr>
            <div class="Formular">
                <form method="post" class="event-formular" enctype="multipart/form-data">

                    <label for="file1">Dateien hinzufügen:</label><br>
                    <input name="file[]" type="file" multiple id="file1"><br>

                    <div class="Formular_Submit">
                        <input type="submit" value="Submit">
                    </div>

                </form>
            </div>

        <?php endif; ?>

    </main>

<?php include("Includes/includesAfterMain.php"); ?>