<?php include("Includes/includesBeforeMain.php"); ?>

<main>
    <div id="upload_status">
        <?php
            if ($upload_status) {
                echo "<h4>$upload_status</h4>";
            }
        ?>
    </div>

    <div class="Formular">
        <form method="post" class="contact-formular" id="picture_Upload_Form" enctype="multipart/form-data">

            <label for="name">Ihr Name:</label><br>
            <input type="text" id="name" name="name" required><br>

            <p>Bitte tragt eine Veranstaltung zur einfacheren Zuordnung ein.</p>
            <label for="eventname">Veranstaltung:</label><br>
            <input type="text" id="eventname" name="eventname" required><br>

            <br>

            Wähle die Bilder, die du hochladen möchtest: <br>
            Technisch bdingt ist es leider nur möglich 20 Bilder auf einmal zu übertragen. <br>
            Solltest du mehr hochladen wollen, bitte ich dich dies mehrere male zu machen. Vielen Dank.<br>
            <input type="file" name="files[]" accept="image/jpeg, image/png, image/gif" multiple>

            <div id="uploadMessage" style="display: none;">
                <h3>
                    Bitte warten Sie, der Upload wurde gestartet und verarbeitet ... <br>
                    Dies kann ein paar Minuten dauern ...
                </h3>
            </div>

            <div class="Formular_Submit">
                <button type="submit" name="submit_upload">Dateien hochladen.</button>
            </div>

        </form>
    </div>
</main>

<?php include("Includes/includesAfterMain.php"); ?>