<?php include("Includes/includesBeforeMain.php"); ?>

<main>
    <div class="Formular">
        <form method="post" class="contact-formular">

            <p>Bitte gib das Passwort für den Fotoupload ein</p>
            <label for="password">Passwort</label><br>
            <input type="password" id="password" name="password" required><br>

            <br>

            <div class="Formular_Submit">
                <button type="submit" name="submit_upload_login">Freigabe</button>
            </div>

        </form>
    </div>
</main>

<?php include("Includes/includesAfterMain.php"); ?>