<?php include("Includes/includesBeforeMain.php"); ?>

<main>
    <div class="home">
        <div class="home-ueberschrift">
            <div style="width: 60%">

            </div>
            <div style="width: 40%" class="home-text">
                <div style="height: 300px">

                </div>
                <div>
                    <p style="color: white; font-weight: bold">Willkommen bei</p>
                    <h1 style="font-size: 3rem">Taekwondo <br>
                        & Allkampf </h1>
                    <h1 style="color: white; font-size: 3rem">Leppersdorf</h1>
                    <p style="color: white; font-weight: bold">Was immer du willst, du kannst es erreichen</p>
                </div>
                <a href="<?php echo App::getBaseURL() ?>trainingszeiten/trainingszeiten" class="home-link-probe">
                    <p> Starte noch heute mit deinem (Probe)Training!</p>
                </a>
            </div>
        </div>
    </div>

    <div class="home-disziplinen-main">
        <div style="width: 90%; display: flex; justify-content: center">
            <a href="<?php echo App::getBaseURL() ?>Ueberuns/schattenkampf"
               class="home-disziplin-schattenkampf">
                <p>Schattenkampf</p>
            </a>

            <a href="<?php echo App::getBaseURL() ?>Ueberuns/Wettkampf"
               class="home-disziplin-wettkampf">
                <p>Wettkampf</p>
            </a>

            <a href="<?php echo App::getBaseURL() ?>Ueberuns/Workout"
               class="home-disziplin-workout">
                <p>Workout</p>
            </a>

            <a href="<?php echo App::getBaseURL() ?>Ueberuns/selbstverteidigung"
               class="home-disziplin-selbstvereidigung">
                <p>Selbstverteidigung</p>
            </a>


        </div>






<!--        <a href="--><?php //echo App::getBaseURL() ?><!--Ueberuns/schattenkampf" class="disziplinen-link">-->
<!--            <div class="disziplinen">-->
<!--                <div>-->
<!--                    <p>Schattenkampf</p>-->
<!--                </div>-->
<!---->
<!--                <div style="height: 300px;">-->
<!--                    <img src="/MediaFiles/Bilder/Home/Formen.jpg" alt="Schattenkampf">-->
<!--                </div>-->
<!--            </div>-->
<!--        </a>-->
<!---->
<!--        <a href="--><?php //echo App::getBaseURL() ?><!--Ueberuns/Wettkampf" class="disziplinen-link">-->
<!--            <div class="disziplinen">-->
<!--                <div>-->
<!--                    <p>Wettkampf</p>-->
<!--                </div>-->
<!--                <div style="height: 300px;">-->
<!--                    <img src="/MediaFiles/Bilder/Home/Wettkampf.jpg" alt="Wettkampf">-->
<!--                </div>-->
<!--            </div>-->
<!--        </a>-->
<!---->
<!--        <a href="--><?php //echo App::getBaseURL() ?><!--Ueberuns/Workout" class="disziplinen-link">-->
<!--            <div class="disziplinen">-->
<!--                <div>-->
<!--                    <p>Workout</p>-->
<!--                </div>-->
<!--                <div style="height: 300px;">-->
<!--                    <img src="/MediaFiles/Bilder/Home/Workout.jpg" alt="Workout">-->
<!--                </div>-->
<!--            </div>-->
<!--        </a>-->
<!---->
<!--        <a href="--><?php //echo App::getBaseURL() ?><!--Ueberuns/selbstverteidigung" class="disziplinen-link">-->
<!--            <div class="disziplinen">-->
<!--                <div>-->
<!--                    <p>Selbstverteidigung</p>-->
<!--                </div>-->
<!--                <div style="height: 300px;">-->
<!--                    <img src="/MediaFiles/Bilder/Home/Selbsverteidigung.jpg" alt="Selbstverteidigung">-->
<!--                </div>-->
<!--            </div>-->
<!--        </a>-->
<!---->
<!--    </div>-->


</main>




<?php include("Includes/includesAfterMain.php"); ?>

