<?php include("Includes/includesBeforeMain.php"); ?>

<main>
    <?php var_dump($_SESSION);?>
    <div class="home">
        <div class="home-placeholder">

        </div>
        <div class="home-ueberschrift">
            <div >
                <div style="height: 300px">

                </div>
                <div class="home-text">
                    <p style="color: white; font-weight: bold">Willkommen bei</p>
                    <h1>Taekwondo <br>
                        & Allkampf </h1>
                    <h1 style="color: white"> Leppersdorf</h1>
                    <p style="font-weight: bold">Was immer du willst, du kannst es erreichen</p>
                </div>
                <a href="<?php echo App::getBaseURL() ?>trainingszeiten/trainingszeiten" class="home-link-probe">
                    <p> Starte noch heute mit deinem (Probe)Training!</p>
                </a>
            </div>
        </div>
    </div>

    <div class="home-disziplinen">

            <a href="<?php echo App::getBaseURL() ?>Ueberuns/schattenkampf"
               class="home-disziplin-schattenkampf">
                <p>Schattenkampf</p>
            </a>

            <a href="<?php echo App::getBaseURL() ?>Ueberuns/Wettkampf"
               class="home-disziplin-wettkampf">
                <p>Wettkampf</p>
            </a>

            <a href="<?php echo App::getBaseURL() ?>Ueberuns/Workout"
               class="home-disziplin-workout">
                <p>Workout</p>
            </a>

            <a href="<?php echo App::getBaseURL() ?>Ueberuns/selbstverteidigung"
               class="home-disziplin-selbstvereidigung">
                <p>Selbstverteidigung</p>
            </a>

    </div>
</main>


<?php include("Includes/includesAfterMain.php"); ?>

