<?php include("Includes/includesBeforeMain.php"); ?>

<main>
    <div class="Impressum">
        <p>
            Taekwondo- Allkampfclub Dresden e.V. <br>
            Am Dreieck 3        <br>
            01454 Leppersdorf<br>
            Deutschland<br>
            <br>
            Tel.: 01727592402<br>
            E-Mail: info@taekwondo-allkampf-leppersdorf.de<br>
            <br>
            Registergericht: Amtsgericht Dresden<br>
            Registernummer: VR 1826<br>

            Vertretungsberechtigte Vorstandsmitglieder: Heinrich Magosch<br>
            Am Klingele 16<br>
            89443 Schwenningen<br>
            <br>
            Plattform der EU-Kommission zur Online-Streitbeilegung: https://ec.europa.eu/odr<br>

            Wir sind zur Teilnahme an einem Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle weder verpflichtet noch bereit.<br>

            Verantwortliche/r i.S.d. § 18 Abs. 2 MStV:<br>
            Heinrich Magosch, Am Klingele 16, 89443 Schwenningen<br>
            <br>
            Realisierung, technische Betreuung und Weiterentwicklung:<br>
            <br>
            Sebastian Kliem<br>
            Winkelwiese 4<br>
            01454 Radeberg<br>
            <br>
            Mobil: 0173 – 38 11 407<br>

            sebastiankliem.sk@gmail.com<br>
            <br><br>
            Design:<br>
            <br>
            Thomas Löbel<br>
            The Web Designer<br>
            Lindenweg 1<br>
            01824 Rosenthal – Bielatal<br>
            <br>
            Mobil:  0172 – 910 222 5<br>
            <br>
            Info@The-Web-Designer.de<br>
            www.The-Web-Designer.de<br>
        </p>
    </div>
</main>




<?php include("Includes/includesAfterMain.php"); ?>