<?php include("Includes/includesBeforeMain.php"); ?>

<main>
    <div class="Motto">
        <h1>Was immer du willst - du kannst es erreichen!</h1>
    </div>

    <div class="Map">
        <h2>Turnhalle Leppersdorf</h2>
        <p>August-Bebel-Straße 14 b, 01454 Wachau</p>
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1251.3310233454408!2d13.961595313201473!3d51.15158292560227!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4709b57202f7e819%3A0x2e6cdd88c4e59d65!2sDRK%20Kindertagesst%C3%A4tte%20Sonnenschein%20Leppersdorf!5e0!3m2!1sde!2sde!4v1661106632539!5m2!1sde!2sde" width="400" height="300" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
    </div>

    <div class="Map">
        <h2>Turnhalle Dresden Rochwitz</h2>
        <p>Hutbergstraße 2, 01326 Dresden</p>
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2508.13629352968!2d13.843220025300996!3d51.05057113923051!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4709c842bb193ae9%3A0xb0ba9a5ffe8f2bad!2s61.%20Grundschule%20Heinrich%20Sch%C3%BCtz%20Dresden%20Rochwitz!5e0!3m2!1sde!2sde!4v1661106505020!5m2!1sde!2sde" width="400" height="300" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
    </div>

    <div class="kontaktdaten">
        <h3>
            Bei Fragen wendet euch gerne an:
        </h3>
        <p>
            Jochen Klarhöfer<br>
            <br>
            E-Mail: info@taekwondo-allkampf-leppersdorf.de<br>
            Telefon: 0172-7592402
        </p>
    </div>

</main>




<?php include("Includes/includesAfterMain.php"); ?>