<?php include("Includes/includesBeforeMain.php"); ?>

<main>
    <?php
        if (array_key_exists('sendMailResponse', $sendMailParameter) && $sendMailParameter["sendMailResponse"] == "true"):
    ?>
        <div class="Kontakt_Email_Success">
            <hr>
            <h2>
                Die E-Mail wurde erfolgreich versendet.
            </h2>
            <hr>
        </div>
    <?php
        endif;
    ?>

    <?php
        if (array_key_exists('sendMailResponse', $sendMailParameter) && $sendMailParameter["sendMailResponse"] == "false"):
    ?>
        <div class="Kontakt_Email_Success">
            <hr>
            <h2>
                Beim Versand der E-Mail ist ein Fehler aufgetreten.<br>
                Bitte versuchen sie es erneut.
            </h2>
            <hr>
        </div>
    <?php
        endif;
    ?>

    <div class="Motto">
        <h1>Was immer du willst - du kannst es erreichen!</h1>
    </div>

    <div class="Map">
        <h2>Turnhalle Leppersdorf</h2>
        <p>August-Bebel-Straße 14 b, 01454 Wachau</p>
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d788.2879211630365!2d13.961732503410534!3d51.151662709472085!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4709b5a68d67f5e5%3A0x6cdab17ad961c7e7!2sTaekwondo%20Allkampf%20Leppersdorf%20-%20Kampfsportverein%20-%20Selbstverteidigung!5e0!3m2!1sde!2sde!4v1676821460183!5m2!1sde!2sde" width="400" height="300" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
    </div>

    <div class="Map">
        <h2>Turnhalle Dresden Rochwitz</h2>
        <p>Hutbergstraße 2, 01326 Dresden</p>
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2508.13629352968!2d13.843220025300996!3d51.05057113923051!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4709c842bb193ae9%3A0xb0ba9a5ffe8f2bad!2s61.%20Grundschule%20Heinrich%20Sch%C3%BCtz%20Dresden%20Rochwitz!5e0!3m2!1sde!2sde!4v1661106505020!5m2!1sde!2sde" width="400" height="300" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
    </div>

    <div class="kontaktdaten">
        <h3>
            Bei Fragen wendet euch gerne an:
        </h3>
        <p>
            Jochen Klarhöfer<br>
            <br>
            E-Mail: info@taekwondo-allkampf-leppersdorf.de<br>
            Telefon: 0172-7592402
        </p>
    </div>

    <h3>
        Oder schreiben sie uns über das Kontaktformular:
    </h3>

    <div class="Formular">
        <form method="post" class="contact-formular">

            <label for="name">Ihr Name:</label><br>
            <input type="text" id="name" name="name"
                <?php
                if (isset($_SESSION)) {
                    if (array_key_exists('contactform', $_SESSION)){
                        if (array_key_exists('name', $_SESSION['contactform'])) {
                            if ($sendMailParameter["sendMailResponse"] == "false") {
                                echo "value=\"" . $_SESSION['contactform']["name"] . "\"";
                            }
                        }
                    }
                }
                ?>
                   required><br>

            <label for="email">Ihre E-Mail-Adresse:</label><br>
            <input type="email" id="email" name="email"
                <?php
                    if (isset($_SESSION)) {
                        if (array_key_exists('contactform', $_SESSION)) {
                            if (array_key_exists('email', $_SESSION['contactform'])) {
                                if ($sendMailParameter["sendMailResponse"] == "false") {
                                    echo "value=\"" . $_SESSION['contactform']["email"] . "\"";
                                }
                            }
                        }
                    }
                ?>
                   required><br>

            <label for="message">Ihre Nachricht:</label><br>
            <textarea id="message" name="message" cols="30" rows="5" wrap="hard"
                    required>
                <?php
                    if (isset($_SESSION)) {
                        if (array_key_exists('contactform', $_SESSION)) {
                            if (array_key_exists('massage', $_SESSION['contactform'])) {
                                if ($sendMailParameter["sendMailResponse"] == "false") {
                                    echo $_SESSION['contactform']["massage"];
                                }
                            }
                        }
                    }


                ?>
            </textarea>

            <br>

            <div class="Formular_Submit">
                <button type="submit">Nachricht senden.</button>
            </div>

        </form>
    </div>
</main>

<?php include("Includes/includesAfterMain.php"); ?>