<?php include("Includes/includesBeforeMain.php"); ?>

<main>
    <div class="Login">
        <form method="post" class="login-formular">
            <p>eMail:</p>
            <label>
                <input type="text" name="email">
            </label>
            <p>Passwort:</p>
            <label>
                <input type="password" name="password">
            </label>

            <input type="submit" value="Log In">

        </form>



    </div>


</main>


<?php include("Includes/includesAfterMain.php"); ?>

