<?php include("Includes/includesBeforeMain.php"); ?>

<main>
    <article>
        <div class="News_Image">
            <img  src="/MediaFiles/Bilder/IMG_20220723_103619.jpg">
        </div>

        <div class="News_Text">
            <h1>
                Lorem Ipsum
            </h1>
            <p>
                lorem ipsum verde
            </p>
            <a href="">Hier weiter lesen</a>
        </div>
    </article>

    <hr>

    <article>
        <div class="News_Image">
            <img  src="/MediaFiles/Bilder/IMG_20220723_104903.jpg">
        </div>

        <div class="News_Text">
            <h1>
                Lorem Ipsum
            </h1>
            <p>
                lorem ipsum verde
            </p>
            <a href="">Hier weiter lesen</a>
        </div>
    </article>
</main>

<?php include("Includes/includesAfterMain.php"); ?>