<?php include("Includes/includesBeforeMain.php"); ?>


    <main>
        <div class="News_Details_Maindiv">
            <div>
                <h2>
                    <?php echo $news['headline'] ?>
                </h2>
            </div>

            <div class="News_Details_Description">
                <?php echo $news['description'] ?>
            </div>

            <?php foreach ($news['documents'] as $file): ?>
                <div class="News_Details_Images">

                    <?php
                        $filename = $file['filename'];
                        $id = $file['id'];
                    ?>

                    <img src="<?php echo "/temp/".$filename ?>" alt="<?php echo $filename ?>">

                    <?php if($canEdit): ?>
                        <div id="News_Deatails_Documents_Delete">
                            <a href="<?php echo App::getBaseURL() ?>news/deleteDocument/fileid/<?php echo $id; ?>/newsId/<?php echo $news['newsId']; ?>">löschen</a>
                        </div>
                    <?php endif; ?>

                </div>

            <?php endforeach; ?>


        </div>
        <?php if($canEdit): ?>

            <hr>
            <div class="Formular">
                <form method="post" class="news-formular" enctype="multipart/form-data">

                    <label for="file1">Bilder hinzufügen:</label><br>
                    <input name="file[]" type="file" multiple id="file1"><br>

                    <div class="Formular_Submit">
                        <input type="submit" value="Submit">
                    </div>

                </form>
            </div>

        <?php endif; ?>

    </main>

<?php include("Includes/includesAfterMain.php"); ?>