<?php include("Includes/includesBeforeMain.php"); ?>

<main>

    <article>
        <div class="News_Image">
            <img  src="/MediaFiles/Bilder/News/Prüfung-Bambinies.jpg" alt="Prüfung-Bambinies">
        </div>

        <div class="News_Text">
            <h1>
                Gürtelprüfung Bambinis
            </h1>
            <p>
                Erste Prüfung bei den Bambinis.
                <br>
                Die 2 teilnehmenden Jungs konnten sich anschließend über den roten Streifen freuen. 🥋
            </p>
        </div>
    </article>

    <hr>

    <article>
        <div class="News_Image">
            <img  src="/MediaFiles/Bilder/News/" alt="Sommercamp Friedrichshafen">
        </div>

        <div class="News_Text">
            <h1>
                Sommercamp Friedrichshafen
            </h1>
            <p>
                Beim Wettkampf-Olympia Stützpunkt haben 10 Nationen vollen Einsatz gezeigt. Mit viel Action und Spaß haben wir 3 Tage mit unseren Kampfpartnern trainiert.
                <br>
                Nach dem Training verbrachten wir unsere Zeit am Bodensee.
                <br>
                Ein großer Dank unsererseits, geht an Nationaltrainer Boris Winkler, Cheftrainer vom TCC Markus Kohlöffel, Pierre Walter und Karina Fohrmann.
            </p>
        </div>
    </article>

    <hr>

    <article>
        <div class="News_Image">
            <img  src="/MediaFiles/Bilder/News/Trainingslager-Brombachsee-2022.jpg" alt="Trainingslager Brombachsee 2022">
        </div>

        <div class="News_Text">
            <h1>
                Trainingslager Brombachsee 2022
            </h1>
            <p>
                Zum 10. mal fand auch in diesem Jahr das Trainingslager am Brombachsee statt. <br>
                Zu diesem Jubiläum hat es sich auch Großmeister Heinrich Magosch (9.DAN Taekwondo, 9.DAN Allkampf-Jitsu) sich nicht nehmen lassen, neben weiteren Trainern einige Einheiten abzuhalten. <br>
                Wir bedanken uns für ein wieder sehr gelungenes Trainingslager bei den Hauptverantwortlichen Pierre Walter und Jens Moehl und deren besseren Hälften.
            </p>
        </div>
    </article>

    <hr>

    <article>
        <div class="News_Image">
            <img  src="" alt="Lehrgang Werdau">
        </div>

        <div class="News_Text">
            <h1>
                Trainerlehrgang und Prüfung Allkampf in Werdau
            </h1>
            <p>
                In der Sportschule Werdau fand vom 15. bis 17.07. der alljährliche Trainerlehrgang statt. <br>
                In den drei Tagen konnten unsere Trainer und unser Trainernachwuchs ihr Wissen vertiefen und ihre Techniken verfeinern. <br>
                Außerdem konnte am Samstag an der DAN-Prüfung teilgenommen werden. Wir gratulieren Jochen Klarhöfer zum 1. DAN und Lea Klarhöfer zum 1. Grad im Allkampf.
            </p>
        </div>
    </article>

    <hr>

    <article>
        <div class="News_Image">
            <img  src="/MediaFiles/Bilder/News/Trainingslager_Heidenau2022.jpg" alt="Trainingslager Heidenau">
        </div>

        <div class="News_Text">
            <h1>
                Sommercamp in Heidenau
            </h1>
            <p>
                Vom 10.06. bis 12.06. fand unser erstes eigenes Trainingslager im Schwimmbad Heidenau statt. <br>
                Zwichen den Zelten und dem Badebecken haben alle fleißig trainiert und gespielt. <br>
                Wir freuen uns auf das nächste Jahr.
            </p>
        </div>
    </article>

    <hr>

    <article>
        <div class="News_Image">
            <img  src="" alt="Vorarlberger Landesmeisterschaften Technik & Vollkontakt">
        </div>

        <div class="News_Text">
            <h1>
                Vorarlberger Landesmeisterschaften Technik & Vollkontakt
            </h1>
            <p>
                Das Wettkampf-Team Landshut & Leppersdorf (L&L) war am 21. Mai in Österreich bei den offenen Vorarlberger Landesmeisterschaften Technik & Vollkontakt erfolgreich am Start.
                <br>
                Es nahmen Sportler aus Österreich, der Schweiz und Deutschland teil.
                <br>
                🥇🥈🏆 am Ende Platz 2 in der Mannschaftswertung
                <br>
                Wir danken den Vorarlberger TKD-Verband in Österreich für die Gastfreundschaft, die Klasse Atmosphäre. Dank an unseren Sportfreunden Pierre Walter, Karina Fuhrmann, Uwe Stenzel... ein tolles Turnier Technik und Vollkontakt.            <!--            <a href="">Hier weiter lesen</a>-->
        </div>
    </article>

    <hr>

    <article>
        <div class="News_Image">
            <img  src="" alt="Breitensportlehrgang Dillingen 2022">
        </div>

        <div class="News_Text">
            <h1>
                Breitensportlehrgang Dillingen 2022
            </h1>
            <p>
                Breitensportlehrgang Dillingen, am 07.05. ausgerichtet von unserem herzlichst bedanktem Großmeister Heinrich Magosch, welcher uns Unterkunft in einer seiner Trainingshallen bot. Neues gelernt, Fähigkeiten erweitert und das mit Spaß und guter Laune.            </p>
            <!--            <a href="">Hier weiter lesen</a>-->
        </div>
    </article>

    <hr>

    <article>
        <div class="News_Image">
            <img  src="" alt="Trainer-Lehrgang Brombachsee 2022">
        </div>

        <div class="News_Text">
            <h1>
                Trainer-Lehrgang Brombachsee 2022
            </h1>
            <p>
                Vom 18. bis 20.02. waren unsere Trainer und Nachwuchs-Trainer am Brombachsee im 1. Taekwondo Winter-Camp. Ein irres Wochenende mit Sportfreunden aus Bayern, Baden-Württemberg. viel gelernt, gekämpft, erlebt, einfach schön. Großen Dank an die Sportschule Pierre Walter Landshut für die Organisation.
            </p>
<!--            <a href="">Hier weiter lesen</a>-->
        </div>
    </article>

    <hr>

    <article>
        <div class="News_Image">
            <img src="/MediaFiles/Bilder/News/Bambinitraining.jpg" alt="Bambinitraining">
        </div>

        <div class="News_Text">
            <h1>
                Bambini-Training Leppersdorf
            </h1>
            <p>


                Ab dem 05.04. bieten wir nun auch für die kleinen ein Training an.

                In dem Kinder-Training fokussieren wir uns vor allem auf die Entwicklung und Förderung der allgemeinen sportlichen Fähigkeiten und die Motorik der Kinder.

                Wir freuen uns auf sportbegeisterte Kinder ab 5 Jahren auch aus allen umgebenen Orten wie z.B. Großnaundorf, Wachau sowie Radeberg, Pulsnitz…

            </p>
<!--            <a href="">Hier weiter lesen</a>-->
        </div>
    </article>
</main>

<?php include("Includes/includesAfterMain.php"); ?>