<?php include("Includes/includesBeforeMain.php"); ?>

<main>
    <div class="table">
        <table>
            <thead>
            <tr>
                <th colspan="4">Trainingszeiten</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td></td>
                <td>Uhrzeit</td>
                <td>Ort</td>
            </tr>
            <tr>
                <td rowspan="2">Dienstag</td>
                <td>16:30 – 17:15 Uhr</td>
                <td>Leppersdorf<br>
                    Bambini</td>
            </tr>
            <tr>
                <td>17:30 – 19:00 Uhr</td>
                <td>Leppersdorf<br>
                    für alle ab 8 Jahre</td>
            </tr>
            <tr>
                <td>Mittwoch</td>
                <td>17:30 – 19:00 Uhr</td>
                <td>Dresden-Rochwitz<br>
                    für alle</td>
            </tr>
            <tr>
                <td>Donnerstag</td>
                <td>18:30 – 20:00 Uhr</td>
                <td>Leppersdorf<br>
                    Jugendliche / Erwachsene</td>
            </tr>
            <tr>
                <td>Freitag</td>
                <td>16:00 – 17:30 Uhr</td>
                <td>Leppersdorf<br>
                    Kinder ab 8 Jahre / Jugendliche</td>
            </tr>
            <tr>
                <td>Samstag</td>
                <td>10:00 – 12:00 Uhr</td>
                <td>Leppersdorf<br>
                    freies Training für alle<br>
                    (vorherige Absprache)</td>
            </tr>
            </tbody>
        </table>

    </div>

    <div class="probetraining">
        Probetrainings sind jederzeit zu den normalen Trainingszeiten möglich. <br>
        Kommt einfach vorbei!
    </div>

    <div class="Hallen">
        <div style="width: 50%">
            <div class="Halle_einzeln">
                <h2>Turnhalle Leppersdorf</h2>
                <p>
                    August-Bebel-Straße 4b
                    <br>
                    01454 Wachau OT Leppersdorf
                </p>
                <img src="/MediaFiles/Bilder/Hallen/Halle_Leppersdorf.png" alt="">
            </div>
            <div class="Halle_einzeln">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1251.3310233454408!2d13.961595313201473!3d51.15158292560227!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4709b57202f7e819%3A0x2e6cdd88c4e59d65!2sDRK%20Kindertagesst%C3%A4tte%20Sonnenschein%20Leppersdorf!5e0!3m2!1sde!2sde!4v1661106632539!5m2!1sde!2sde" width="400" height="300" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
            </div>
        </div>
        <div style="width: 50%">
            <div class="Halle_einzeln">
                <h2>Turnhalle Rochwitz</h2>
                <p>
                    Hutbergstraße 2
                    <br>
                    01326 Dresden OT Rochwitz
                </p>
                <img src="/MediaFiles/Bilder/Hallen/Halle_Rochwitz.png" alt="">
            </div>
            <div class="Halle_einzeln">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2508.13629352968!2d13.843220025300996!3d51.05057113923051!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4709c842bb193ae9%3A0xb0ba9a5ffe8f2bad!2s61.%20Grundschule%20Heinrich%20Sch%C3%BCtz%20Dresden%20Rochwitz!5e0!3m2!1sde!2sde!4v1661106505020!5m2!1sde!2sde" width="400" height="300" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
            </div>
        </div>
    </div>

    <div class="Info">
        <h3>Was musst Du mitbringen:</h3>
        <ul>
            <li>einen Trainingsanzug (lange Hose, T-Shirt) oder Dobok</li>
            <li>etwas zu trinken!</li>
        </ul>
        <p>Wir trainieren barfuß!</p>
    </div>

    <div class="anmeldebogen">
        <div style="text-align: center">
            Hier ist unser Anmeldebogen zum Download:
        </div>
        <div style="display: flex; justify-content: center">
            <a href="/MediaFiles/Anmeldebogen.pdf"><img src="/MediaFiles/PDF_icon.png" alt="Download"></a>
        </div>
    </div>
    </main>




<?php include("Includes/includesAfterMain.php"); ?>